export const APP_INIT = "APP_INIT";
export const NUMEROFSEAT_UPDATED = "NUMEROFSEAT_UPDATED";
export const SEATING_TYPE_CHANGED = "SEATING_TYPE_CHANGED";
export const SEAT_SELECTED = "SEAT_SELECTED";
export const UPDATE_CLUBMATRIX = "UPDATE_CLUBMATRIX";
export const UPDATE_EXECUTIVEMATRIX = "UPDATE_EXECUTIVEMATRIX";
